// This file autogenerated by generate-asset-types.js
// Do not modify it by hand. Any changes will be overwritten.
const sounds = {
  snap: require("url:./audio/snap.flac"),
  sheetSnap: require("url:./audio/sheet_snap.wav"),
  boomSlam: require("url:./audio/boom_slam.wav"),
};
export type SoundName = keyof typeof sounds;

const images = {
  vendoviIsland: require("url:./levels/vendovi-island.svg"),
  default: require("url:./levels/default.svg"),
  favicon: require("url:./images/favicon.png"),
};
export type ImageName = keyof typeof images;

const fonts = {};
export type FontName = keyof typeof fonts;

const levels = {
  vendoviIsland: require("./levels/vendovi-island.level.json"),
  sanJuanIslands: require("./levels/san-juan-islands.level.json"),
  islesOfScilly: require("./levels/isles-of-scilly.level.json"),
  default: require("./levels/default.level.json"),
  apostleIslands: require("./levels/apostle-islands.level.json"),
};
export type LevelName = keyof typeof levels;

const entityDefs = {};
export type EntityDefName = keyof typeof entityDefs;

const jsonBlobs = {};

const wavemeshes = {
  vendoviIsland: require("url:./levels/vendovi-island.wavemesh"),
  sanJuanIslands: require("url:./levels/san-juan-islands.wavemesh"),
  islesOfScilly: require("url:./levels/isles-of-scilly.wavemesh"),
  default: require("url:./levels/default.wavemesh"),
  apostleIslands: require("url:./levels/apostle-islands.wavemesh"),
};
export type WavemeshName = keyof typeof wavemeshes;

export const RESOURCES = {
  sounds,
  images,
  fonts,
  levels,
  entityDefs,
  jsonBlobs,
  wavemeshes,
};
