// This file autogenerated by generate-asset-types.js
// Do not modify it by hand. Any changes will be overwritten.
const sounds = {
  snap: require("url:./audio/snap.flac"),
  sheetSnap: require("url:./audio/sheet_snap.wav"),
  boomSlam: require("url:./audio/boom_slam.wav")
};
export type SoundName = keyof typeof sounds;

const images = {
  vendoviIsland: require("url:./levels/vendovi-island.svg"),
  default: require("url:./levels/default.svg"),
  favicon: require("url:./images/favicon.png")
};
export type ImageName = keyof typeof images;

const fonts = {
  spectralLight: require("url:./fonts/Spectral-Light.woff2"),
  spectralRegular: require("url:./fonts/Spectral-Regular.woff2"),
  spectralSemiBold: require("url:./fonts/Spectral-SemiBold.woff2"),
  tangerineBold: require("url:./fonts/Tangerine-Bold.woff2"),
  tangerineRegular: require("url:./fonts/Tangerine-Regular.woff2"),
  youngSerifRegular: require("url:./fonts/YoungSerif-Regular.woff2")
};
export type FontName = keyof typeof fonts;

const levels = {
  vendoviIsland: require("./levels/vendovi-island.level.json"),
  sanJuanIslands: require("./levels/san-juan-islands.level.json"),
  islesOfScilly: require("./levels/isles-of-scilly.level.json"),
  default: require("./levels/default.level.json"),
  apostleIslands: require("./levels/apostle-islands.level.json")
};
export type LevelName = keyof typeof levels;

const terrains = {
  vendoviIsland: require("url:./levels/vendovi-island.terrain"),
  sanJuanIslands: require("url:./levels/san-juan-islands.terrain"),
  islesOfScilly: require("url:./levels/isles-of-scilly.terrain"),
  apostleIslands: require("url:./levels/apostle-islands.terrain")
};
export type TerrainName = keyof typeof terrains;

const entityDefs = {

}
export type EntityDefName = keyof typeof entityDefs;

const jsonBlobs = {

};

const wavemeshes = {
  vendoviIsland: require("url:./levels/vendovi-island.wavemesh"),
  sanJuanIslands: require("url:./levels/san-juan-islands.wavemesh"),
  islesOfScilly: require("url:./levels/isles-of-scilly.wavemesh"),
  default: require("url:./levels/default.wavemesh"),
  apostleIslands: require("url:./levels/apostle-islands.wavemesh")
};
export type WavemeshName = keyof typeof wavemeshes;

const windmeshes = {
  vendoviIsland: require("url:./levels/vendovi-island.windmesh"),
  sanJuanIslands: require("url:./levels/san-juan-islands.windmesh"),
  islesOfScilly: require("url:./levels/isles-of-scilly.windmesh"),
  default: require("url:./levels/default.windmesh"),
  apostleIslands: require("url:./levels/apostle-islands.windmesh")
};
export type WindmeshName = keyof typeof windmeshes;

export const RESOURCES = { sounds, images, fonts, levels, terrains, entityDefs, jsonBlobs, wavemeshes, windmeshes };
