// This file autogenerated by generate-asset-types.ts
// Do not modify it by hand. Any changes will be overwritten.
declare const terrain_apostleIslands: string;
export default terrain_apostleIslands;
