// This file autogenerated by generate-asset-types.ts
// Do not modify it by hand. Any changes will be overwritten.
declare const windmesh_islesOfScilly: string;
export default windmesh_islesOfScilly;
