//! Build script — auto-generates `src/protocol.rs` from the canonical
//! TypeScript protocol module so layout constants stay in sync between
//! the TS / Rust / WGSL boundary.
//!
//! The TS source of truth is
//! `src/game/world/query/query-worker-protocol.ts`. We extract a fixed
//! set of `export const NAME = <number>` lines via a simple regex and
//! emit matching `pub const NAME: usize = <value>;` into
//! `src/protocol.rs` (committed to the repo so editors / rust-analyzer
//! see it; regenerated on every cargo build).
//!
//! If a constant is missing in the TS file the build fails — a
//! deliberate hard error so the two sides can never silently drift.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Constants we expect to mirror from `query-worker-protocol.ts`.
const REQUIRED_CONSTANTS: &[&str] = &[
    "STRIDE_PER_POINT",
    "PARAMS_FLOATS_PER_CHANNEL",
    "FLOATS_PER_MODIFIER",
    "MAX_WAVE_SOURCES",
    "MAX_MODIFIERS",
];

fn main() {
    // Locate the TS protocol file relative to the crate's manifest dir.
    // CARGO_MANIFEST_DIR is `<repo>/pipeline/query-wasm`; the protocol
    // file lives at `<repo>/src/game/world/query/query-worker-protocol.ts`.
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("CARGO_MANIFEST_DIR has no grandparent (expected <repo>/pipeline/query-wasm)");
    let ts_path = repo_root
        .join("src")
        .join("game")
        .join("world")
        .join("query")
        .join("query-worker-protocol.ts");

    println!("cargo:rerun-if-changed={}", ts_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let ts_source = fs::read_to_string(&ts_path).unwrap_or_else(|e| {
        panic!(
            "build.rs: cannot read TS protocol file at {}: {}",
            ts_path.display(),
            e
        )
    });

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by `build.rs` from\n");
    out.push_str("// `src/game/world/query/query-worker-protocol.ts`.\n");
    out.push_str("// DO NOT EDIT — change the TS file and rebuild instead.\n\n");
    out.push_str("//! Shared layout constants mirrored from the TypeScript protocol module.\n");
    out.push_str("//! See `src/game/world/query/query-worker-protocol.ts` for the canonical\n");
    out.push_str("//! definitions and per-constant documentation.\n\n");

    for &name in REQUIRED_CONSTANTS {
        let value = extract_constant(&ts_source, name).unwrap_or_else(|| {
            panic!(
                "build.rs: required constant `{}` not found in {} (expected `export const {} = <number>`)",
                name,
                ts_path.display(),
                name,
            )
        });
        out.push_str(&format!("pub const {}: usize = {};\n", name, value));
    }

    let dest = manifest_dir.join("src").join("protocol.rs");

    // Avoid clobbering with an identical write — keeps mtimes stable so
    // editors / IDEs don't see spurious file-change events on no-op
    // builds.
    let needs_write = match fs::read_to_string(&dest) {
        Ok(existing) => existing != out,
        Err(_) => true,
    };
    if needs_write {
        fs::write(&dest, out).unwrap_or_else(|e| {
            panic!(
                "build.rs: cannot write generated protocol.rs to {}: {}",
                dest.display(),
                e
            )
        });
    }
}

/// Extract the integer value of `export const NAME = <number>;` (or
/// `= <number>` followed by anything) from `source`. Returns `None` if
/// the constant is absent or its value isn't a plain non-negative
/// integer literal.
fn extract_constant(source: &str, name: &str) -> Option<u64> {
    // Search for `export const <name>` and then the first integer-ish
    // token after the `=`. Cheap and good enough for our hand-written
    // protocol module — we control both sides of this contract.
    let needle = format!("export const {} ", name);
    let start = source.find(&needle)?;
    let after = &source[start + needle.len()..];
    // Skip past `= ` (or `=` plus optional whitespace).
    let eq = after.find('=')?;
    let mut rest = after[eq + 1..].trim_start();
    // Must be a digit now; anything else (e.g. an expression) means the
    // constant isn't a plain numeric literal and we shouldn't pretend
    // we can mirror it.
    let mut digits = String::new();
    while let Some(c) = rest.chars().next() {
        if c.is_ascii_digit() {
            digits.push(c);
            rest = &rest[1..];
        } else {
            break;
        }
    }
    if digits.is_empty() {
        return None;
    }
    digits.parse::<u64>().ok()
}
