// AUTO-GENERATED by `build.rs` from
// `src/game/world/query/query-worker-protocol.ts`.
// DO NOT EDIT — change the TS file and rebuild instead.

//! Shared layout constants mirrored from the TypeScript protocol module.
//! See `src/game/world/query/query-worker-protocol.ts` for the canonical
//! definitions and per-constant documentation.

pub const STRIDE_PER_POINT: usize = 2;
pub const PARAMS_FLOATS_PER_CHANNEL: usize = 128;
pub const FLOATS_PER_MODIFIER: usize = 14;
pub const MAX_WAVE_SOURCES: usize = 8;
pub const MAX_MODIFIERS: usize = 16384;
